import { Component } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { IonButton, IonContent, IonIcon, IonInput } from '@ionic/angular/standalone';
import { CHAT_MESSAGES } from '../../core/data/mock-data';
import { AppHeaderComponent, BottomTabsComponent, ChatBubbleComponent } from '../../shared/components/ui-kit.components';

@Component({ selector: 'app-chat', standalone: true, imports: [IonButton, IonContent, IonIcon, IonInput, AppHeaderComponent, BottomTabsComponent, ChatBubbleComponent], styleUrls: ['../pages.scss'], template: `
<app-header [showBack]="mode === 'document'" [backLink]="mode === 'document' ? '/documents/subnetting' : '/dashboard'"></app-header><ion-content class="nexus-content chat-content"><span class="eyebrow">{{ mode === 'document' ? 'Chat contextual' : 'Asistente personal' }}</span><h1 class="page-title">{{ mode === 'document' ? 'Chat con documento' : 'Nexus Chat' }}</h1><p class="page-subtitle">{{ mode === 'document' ? 'Las respuestas utilizan únicamente el contenido seleccionado.' : 'Piensa, estudia y construye con tu segundo cerebro.' }}</p>@if (mode === 'document') {<div class="document-context"><ion-icon name="document-text-outline"></ion-icon><div><strong>Guía de subnetting.pdf</strong><br>24 páginas conectadas</div></div>}@for (message of messages; track $index) {<app-chat-bubble [role]="message.role" [text]="message.text"></app-chat-bubble>}</ion-content><div class="fixed-composer with-tabs glass"><ion-input placeholder="Escribe tu pregunta..."></ion-input><ion-button aria-label="Enviar"><ion-icon name="arrow-up"></ion-icon></ion-button></div><app-bottom-tabs></app-bottom-tabs>` })
export class ChatPage { mode: 'general' | 'document'; messages = CHAT_MESSAGES; constructor(route: ActivatedRoute) { this.mode = route.snapshot.data['mode'] ?? 'general'; } }
