import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: 'splash', loadComponent: () => import('./pages/splash/splash.page').then(m => m.SplashPage) },
  { path: 'onboarding', loadComponent: () => import('./pages/onboarding/onboarding.page').then(m => m.OnboardingPage) },
  { path: 'login', loadComponent: () => import('./pages/auth/auth.page').then(m => m.AuthPage), data: { mode: 'login' } },
  { path: 'register', loadComponent: () => import('./pages/auth/auth.page').then(m => m.AuthPage), data: { mode: 'register' } },
  { path: 'dashboard', loadComponent: () => import('./pages/dashboard/dashboard.page').then(m => m.DashboardPage) },
  { path: 'workspaces', loadComponent: () => import('./pages/workspaces/workspaces.page').then(m => m.WorkspacesPage) },
  { path: 'subjects/:id', loadComponent: () => import('./pages/subject-detail/subject-detail.page').then(m => m.SubjectDetailPage) },
  { path: 'library', loadComponent: () => import('./pages/library/library.page').then(m => m.LibraryPage) },
  { path: 'upload', loadComponent: () => import('./pages/upload/upload.page').then(m => m.UploadPage) },
  { path: 'documents/:id', loadComponent: () => import('./pages/document-detail/document-detail.page').then(m => m.DocumentDetailPage) },
  { path: 'summary', loadComponent: () => import('./pages/summary/summary.page').then(m => m.SummaryPage) },
  { path: 'chat', loadComponent: () => import('./pages/chat/chat.page').then(m => m.ChatPage), data: { mode: 'general' } },
  { path: 'chat/document', loadComponent: () => import('./pages/chat/chat.page').then(m => m.ChatPage), data: { mode: 'document' } },
  { path: 'quiz-generator', loadComponent: () => import('./pages/quiz-generator/quiz-generator.page').then(m => m.QuizGeneratorPage) },
  { path: 'quiz', loadComponent: () => import('./pages/quiz/quiz.page').then(m => m.QuizPage) },
  { path: 'quiz-result', loadComponent: () => import('./pages/quiz-result/quiz-result.page').then(m => m.QuizResultPage) },
  { path: 'flashcards', loadComponent: () => import('./pages/flashcards/flashcards.page').then(m => m.FlashcardsPage) },
  { path: 'tasks', loadComponent: () => import('./pages/tasks/tasks.page').then(m => m.TasksPage) },
  { path: 'study-plan', loadComponent: () => import('./pages/study-plan/study-plan.page').then(m => m.StudyPlanPage) },
  { path: 'profile', loadComponent: () => import('./pages/profile/profile.page').then(m => m.ProfilePage) },
  { path: 'settings', loadComponent: () => import('./pages/settings/settings.page').then(m => m.SettingsPage) },
  { path: '', redirectTo: 'splash', pathMatch: 'full' },
  { path: '**', redirectTo: 'dashboard' },
];
